### ISSUE TITLE
Malicious crafted url allows to redirect to another domain

### ISSUE THREAD

**Issue by Tefnet** [daringway/terraform-aws-cloudfront-viewer-request-lambda#3]
Creating url with "//" and missing trailing slash allows you to automatically redirect to another domain. For example:
https://www.mydomain.com//example.com/foo
Generates redirect:
Location: //example.com/foo/

**Comment by zackdotcomputer** [comment]
This is only if on has `append_slash` enabled. I think the fix would be to manually check the `olduri` variable for `.startsWith("//")` and, if so, drop that first character before transforming it.

(apologies for driving-by and not PR'ing - just researching for a different project and saw this.)

**Comment by wderezin** [comment]
I was able to reproduce the error.   When the redirect happen the location starts with `//example.com` so the browser sees that website even though the http/https is missing. 

@Tefnet sorry for the delay in my response.  The issue got lost in my large inbox of notifications. 
@zackdotcomputer a comment is much better then no comment.  Thank you.

**Comment by wderezin** [comment]
released in v1.2.3
